### ISSUE TITLE
I want to use this plug-in at opera.

### ISSUE THREAD

**Issue by s96281** [krismuniz/minimo#16]
As this title said, I want to use Minimo at opera. I've been try the "Install Chrome Extensions" is an offical tool that can install plug-in from chrome app store. Actually, I install Minimo sucessed, but when I open new tap on Opera. It does't change! So I apply to let Minimo support Opera browser. Thx

**Comment by theRealPadster** [comment]
I know Vivaldi has an option you need to toggle to allow extensions to control the new tab page, so maybe Opera has something similar?

**Comment by krismuniz** [comment]
Hello! As of today Opera does not allow users to change its start page. At least not easily. 

Until Opera offers first-class support for custom new tab pages I'm afraid we won't be able to have Minimo on Opera.
