### ISSUE TITLE
Use ctrl+click or cmd+click to open a bookmark in a new tab

### ISSUE THREAD

**Issue by rubenduiveman** [krismuniz/minimo#18]
First of all, compliments on the great extension.
I'd like to be able to use ctrl+click or cmd+click to open a bookmark in a new tab. Right now, the bookmark is actually opened in a new tab (in the background, as preferred), but the current tab also navigates to that URL.

I'd like for links clicked with ctrl+click or cmd+click to open in a new tab in the background.

Thanks in advance!

**Comment by krismuniz** [comment]
Hello @rubenduiveman! This is definitely unexpected behavior that will be fixed.

Thank you very much for reporting it!

**Comment by krismuniz** [comment]
This issue has been fixed in https://github.com/krismuniz/minimo/commit/f235f7e43a884978b2b8f24eb3863f723a7bc0bd and published to the Chrome Webstore as `v1.1.4` :)

It should automatically update on your browser soon!
