### ISSUE TITLE
Option to deactivate unneeded features

### ISSUE THREAD

**Issue by schaafjs** [krismuniz/minimo#22]
The goal of this extension is to be as minimal as possible. That's why I think it would be only fair to give the users the option to deactivate all the features that they don't need.
I for example don't need my synced tabs to show up, nor do I need to see the current network speed. The ability to remove the synced tabs view was already mentioned [here](https://github.com/krismuniz/minimo/issues/8).

**Comment by Mirabeau2Code** [comment]
Everyone has their own use of this project.
Its simplicity, but also these features are a must.
For example, what is most useful for me is the current tab sharing on other devices to change device and continue quickly.

Having a configuration of on/off of features would, of course, be interesting

**Comment by krismuniz** [comment]
Thank you for the feedback! I'm working on adding on/off switches for all these features. It will be as minimal as you want.

**Comment by Mirabeau2Code** [comment]
I had a little time in front of me and I made the changes.
By cons I know badly badly git ... and do not know how to send the changes ...
![Screenshot_2](https://user-images.githubusercontent.com/32990546/59544606-6a2d1200-8f13-11e9-94b0-7ed66a2dd65c.png)

**Comment by Mirabeau2Code** [comment]
I send you file on twitter but i put them here to... hope this help
index.js : https://pastebin.com/YhXKeiMN
new-tab-page.html : https://pastebin.com/626FByp1
 load-theme.js: https://pastebin.com/JgjziqhN
popup.js: https://pastebin.com/Vxe8ZsBt

**Comment by Mirabeau2Code** [comment]
More simple with **diff patch files** to view the change ;) :
 index.js.path : https://pastebin.com/vrDrbx3i
new-tab-page.html.path: https://pastebin.com/aNYN52pU
load-theme.js.patch : https://pastebin.com/6kgJcmAF
popup.js.patch: https://pastebin.com/bHhGh6XM

**Comment by krismuniz** [comment]
I just published [v1.2.0](https://github.com/krismuniz/minimo/blob/master/CHANGELOG.md) of Minimo that fixes this issue. It will be published sometime this week (going through review process).

**Comment by schaafjs** [comment]
Thank you both very much!

**Comment by sahithyandev** [comment]
I just installed Minimo and it's awesome. I also want to hide the "Shortcuts bar".
But I don't see an option on the "customize" page.
Are there any plans on implementing it?
