### ISSUE TITLE
Ability to have multiple time zones

### ISSUE THREAD

**Issue by donnavitan** [krismuniz/minimo#23]
As someone who works with people in different locations, I want to have a simple and quick way to see the time here and there, so that I can quickly check the time difference

**Describe the solution you'd like**
I want another clock beside the one shown (current local time).

**Describe alternatives you've considered**
I've considered not using this extension at all but I like the clean, minimal look.

**Comment by krismuniz** [comment]
This is a great suggestion! Thank you @donnavitan, I'll probably work on this soon!

**Comment by krismuniz** [comment]
Hello @donnavitan this has been released in [v1.3.0](https://github.com/krismuniz/minimo/releases/tag/v1.3.0)!! 

It is currently in review and will be slowly rolling out for current users during the week. Thank you for your contribution!
