### ISSUE TITLE
Wrong Battery %

### ISSUE THREAD

**Issue by raghav4** [krismuniz/minimo#26]
My battery is at 83% and **minimo** is still stuck and showing it to be 100%. How can I fix it?

**Comment by krismuniz** [comment]
Hello @raghav4 could you share info about your device, OS, and browser?

- Device: [e.g. Macbook Pro, ]
 - OS: [e.g. macOS Mojave 10.14.4 / Windows 10 Pro Version 1909]
 - Browser & Browser Version: [e.g. Chrome 74 / Brave v1.0.1]

**Comment by raghav4** [comment]
Thanks @krismuniz, the issue was with the **Brave**[1.0.1], it is working fine with Google Chrome!
