### ISSUE TITLE
Leaving writing mode causes weird scroll glitch

### ISSUE THREAD

**Issue by fr3fou** [krismuniz/minimo#27]
**Describe the bug**
If I go into write mode and then leave it, I get this result afterwards:
![image](https://user-images.githubusercontent.com/1344906/104104460-061a2d80-52b1-11eb-8e08-57ac425c014f.png)
The issue also occurs without the custom CSS

**To Reproduce**
1. Go into write mode
2. Leave it

**Expected behavior**
I expect not to have the weird scroll glitch.

**Desktop (please complete the following information):**
Chrome 87.0.4280.88
Windows 10

**Comment by krismuniz** [comment]
Hello @fr3fou, I just pushed a fix to this issue. Once the update is approved by the Chrome Web Store team, it will be distributed to all users.

Thank you for contributing to Minimo!
