### ISSUE TITLE
Right-click not working

### ISSUE THREAD

**Issue by hanmun** [krismuniz/minimo#35]
**Describe the bug**
First of all, thank you for this plugin. I love it! The problem i'm having is the right-click option suddenly stopped working so I can't access any of the settings or writing mode.

**Screenshots**
https://prnt.sc/3hiZ5G2d-nws

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Versión 109.0.5414.75 (Build official) (64 bits)

**Comment by rashedarman** [comment]
Same here, and it shows these errors in console.

![image](https://user-images.githubusercontent.com/78993606/213023852-133771fd-3565-4ee9-be4f-d2def3cdb4a3.png)

**Comment by krismuniz** [comment]
Will work on it!

**Comment by krismuniz** [comment]
Fixed on: 

- https://github.com/krismuniz/minimo/commit/2e7bebdd939eeb218653de6f3a83957a94299779
- https://github.com/krismuniz/minimo/commit/c292162572c50fa36db7f8df083ff8abb6d39fc4

I just published the update (version `1.4.2`) and it will be rolled out as soon as Chrome Webstore's review team approves it. Thank you for your patience!

**Comment by appel** [comment]
Much appreciated, @krismuniz!

**Comment by hanmun** [comment]
@krismuniz Thank you so much!
