### ISSUE TITLE
"chrome-extension" Shortcuts URL fail in new-tab-page.html

### ISSUE THREAD

**Issue by hye** [krismuniz/minimo#4]
I added a shortcut for extension **toby** `chrome-extension://hddnkoipeenegfoeaoibdmnaalmgkpip/toby.html`

It will open correctly in **Minimo**'s **Popup**, but not in **new-tab-page.html**.

I may found why, **popup** treat the URL with `chrome.tabs.create` while **new tab page** just as a html link.

**Comment by krismuniz** [comment]
Alright, looks like a bug to me! Will fix for next release 🙂

Thank you!

**Comment by krismuniz** [comment]
This issue has been resolved and the fix will be released soon! 👍
